
package View;

import Model.Funcionario;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

public class CadastroFuncionario extends javax.swing.JFrame {

    private Funcionario objfuncionario;
    
    
    public CadastroFuncionario() {
        initComponents();
        this.objfuncionario = new Funcionario();
        jPasswordField_senha.setEchoChar('*');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        label_nome = new javax.swing.JLabel();
        label_cpf = new javax.swing.JLabel();
        label_telefone = new javax.swing.JLabel();
        label_senha = new javax.swing.JLabel();
        btn_cancelar = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();
        field_nome = new javax.swing.JTextField();
        label_idade = new javax.swing.JLabel();
        jLabel_codigo = new javax.swing.JLabel();
        jLabel_rg = new javax.swing.JLabel();
        jFormattedTextField_rg = new javax.swing.JFormattedTextField();
        jFormattedTextField_cpf = new javax.swing.JFormattedTextField();
        jFormattedTextField_datanascimento = new javax.swing.JFormattedTextField();
        jFormattedTextField_telefone = new javax.swing.JFormattedTextField();
        jPasswordField_senha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_endereco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_idade = new javax.swing.JTextField();
        jToggleButton_mostrarsenha = new javax.swing.JToggleButton();
        jFormattedTextField_codigo = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Funcionario");

        label_nome.setText("Nome :");

        label_cpf.setText("CPF :");

        label_telefone.setText("Telefone :");

        label_senha.setText("Senha :");

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_cadastrar.setText("Cadastrar");
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });

        label_idade.setText("Data de nasc :");

        jLabel_codigo.setText("Cod.");

        jLabel_rg.setText("RG:");

        try {
            jFormattedTextField_rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextField_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFormattedTextField_datanascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField_datanascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField_datanascimentoKeyReleased(evt);
            }
        });

        try {
            jFormattedTextField_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jPasswordField_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_senhaActionPerformed(evt);
            }
        });

        jLabel1.setText("Endereco:");

        jTextField_endereco.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel2.setText("Idade");

        jToggleButton_mostrarsenha.setText("Mostrar");
        jToggleButton_mostrarsenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton_mostrarsenhaMouseClicked(evt);
            }
        });

        try {
            jFormattedTextField_codigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_codigo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFormattedTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_nome)
                                    .addComponent(field_nome)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_rg)
                                    .addComponent(jFormattedTextField_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label_cpf)
                                    .addComponent(jFormattedTextField_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1)
                            .addComponent(jTextField_endereco))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(btn_cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextField_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(121, 121, 121))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField_datanascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label_idade)
                            .addComponent(label_telefone))
                        .addGap(121, 121, 121))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cadastrar)
                        .addGap(115, 115, 115))))
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPasswordField_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton_mostrarsenha))
                    .addComponent(label_senha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_codigo)
                            .addComponent(label_nome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_rg)
                            .addComponent(label_cpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextField_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_idade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField_datanascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(label_telefone)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_endereco)
                    .addComponent(jFormattedTextField_telefone))
                .addGap(26, 26, 26)
                .addComponent(label_senha)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton_mostrarsenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_cadastrar))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        try {
            // recebendo e validando dados da interface gr�fica.
            String nome = "";
            String cpf = "";
            String telefone = "";
            String senha = "";
            String datadenascimento = "";
            String codigo = "";
            String rg = "";
            String endereco = "";

            if (this.field_nome.getText().length() < 2) {
                throw new Mensagens("O Nome deve conter ao menos 2 caracteres.");
            } else {
                nome = this.field_nome.getText();
            }

            if (this.jFormattedTextField_cpf.getText().length() < 11) {
                throw new Mensagens("Número de digitos no CPF insuficiente.");
            } else {
                cpf = this.jFormattedTextField_cpf.getText();
            }
            
            if (this.jFormattedTextField_telefone.getText().length() < 2) {
                throw new Mensagens("O Telefone deve conter ao menos 2 caracteres.");
            } else {
                telefone = this.jFormattedTextField_telefone.getText();
            }

            if (this.jPasswordField_senha.getText().length() <= 1) {
                throw new Mensagens("A Senha deve ser número e maior que um.");
            } else {
                senha = this.jPasswordField_senha.getText();
            }
            
            if (this.jFormattedTextField_datanascimento.getText().length() <= 5) {
                throw new Mensagens("A data de nascimento deve ser um número maior que 0.");
            } else {
                datadenascimento = this.jFormattedTextField_datanascimento.getText();
                
            }
            
            if (this.jFormattedTextField_codigo.getText().length() <= 6) {
                throw new Mensagens("O Codigo deve ser um número maior que 6.");
            } else {
                codigo = this.jFormattedTextField_codigo.getText();
                
            }
            
            if (this.jFormattedTextField_rg.getText().length() <= 6) {
                throw new Mensagens("O RG deve ser um número maior que 6.");
            } else {
                rg = this.jFormattedTextField_rg.getText();
                
            }
            
            if (this.jTextField_endereco.getText().length() <= 0) {
                throw new Mensagens("O endereco deve ser maior que 0.");
            } else {
                endereco = this.jTextField_endereco.getText();
                
            }

            // envia os dados para o Controlador cadastrar
            if (this.objfuncionario.InsertFuncionarioBD(cpf, telefone, senha, nome, datadenascimento, codigo, rg, endereco)) {
                JOptionPane.showMessageDialog(rootPane, "Funcionario Cadastrado com Sucesso!");

                // limpa campos da interface
                this.field_nome.setText("");
                this.jFormattedTextField_cpf.setText("");
                this.jFormattedTextField_telefone.setText("");   
                this.jPasswordField_senha.setText("");
                this.jFormattedTextField_datanascimento.setText("");
                this.jFormattedTextField_codigo.setText("");
                this.jFormattedTextField_rg.setText("");
                this.jTextField_endereco.setText("");
                

            }

            System.out.println(this.objfuncionario.getMinhaLista().toString());

        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um número.");
        }
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    private void jPasswordField_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_senhaActionPerformed

    private void jFormattedTextField_datanascimentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_datanascimentoKeyReleased
        // TODO add your handling code here:
        DateTimeFormatter date = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    LocalDate dataNascimento = LocalDate.parse(jFormattedTextField_datanascimento.getText(), date);
    LocalDate dataAtual = LocalDate.now();
    Period periodo = Period.between(dataNascimento,dataAtual);
    String Resultado = (periodo.getYears()+ " Anos "  + periodo.getMonths() + " Meses"+" e " +  periodo.getDays() + " dias");
    jTextField_idade.setText(Resultado);
    }//GEN-LAST:event_jFormattedTextField_datanascimentoKeyReleased

    private void jToggleButton_mostrarsenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton_mostrarsenhaMouseClicked
        // TODO add your handling code here:
        if(jToggleButton_mostrarsenha.isSelected()){
            jPasswordField_senha.setEchoChar((char)0);
            jToggleButton_mostrarsenha.setText("Esconder");
        }
        else{
            jPasswordField_senha.setEchoChar('*');
            jToggleButton_mostrarsenha.setText("Mostrar");
        }
    }//GEN-LAST:event_jToggleButton_mostrarsenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField field_nome;
    private javax.swing.JFormattedTextField jFormattedTextField_codigo;
    private javax.swing.JFormattedTextField jFormattedTextField_cpf;
    private javax.swing.JFormattedTextField jFormattedTextField_datanascimento;
    private javax.swing.JFormattedTextField jFormattedTextField_rg;
    private javax.swing.JFormattedTextField jFormattedTextField_telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_codigo;
    private javax.swing.JLabel jLabel_rg;
    private javax.swing.JPasswordField jPasswordField_senha;
    private javax.swing.JTextField jTextField_endereco;
    private javax.swing.JTextField jTextField_idade;
    private javax.swing.JToggleButton jToggleButton_mostrarsenha;
    private javax.swing.JLabel label_cpf;
    private javax.swing.JLabel label_idade;
    private javax.swing.JLabel label_nome;
    private javax.swing.JLabel label_senha;
    private javax.swing.JLabel label_telefone;
    // End of variables declaration//GEN-END:variables
}
