/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Funcionario;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GerenciarFuncionario extends javax.swing.JFrame {

    private Funcionario objfuncionario;
    
    public GerenciarFuncionario() {
        initComponents();
        this.objfuncionario = new Funcionario(); // carrega objaluno de aluno
        this.carregaTabela();
        jPasswordField_senha.setEchoChar('*');
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableFuncionario = new javax.swing.JTable();
        btn_cancelar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_apagar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField_codigo = new javax.swing.JFormattedTextField();
        jLabel_nome = new javax.swing.JLabel();
        jTextField_nome = new javax.swing.JTextField();
        jLabel_datanascimento = new javax.swing.JLabel();
        jFormattedTextField_datanascimento = new javax.swing.JFormattedTextField();
        jLabel_rg = new javax.swing.JLabel();
        jFormattedTextField_rg = new javax.swing.JFormattedTextField();
        jLabel_cpf = new javax.swing.JLabel();
        jFormattedTextField_cpf = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_idade = new javax.swing.JTextField();
        jLabel_endereco = new javax.swing.JLabel();
        jTextField_endereco = new javax.swing.JTextField();
        jLabel_telefone = new javax.swing.JLabel();
        jFormattedTextField_telefone = new javax.swing.JFormattedTextField();
        jLabel_senha = new javax.swing.JLabel();
        jPasswordField_senha = new javax.swing.JPasswordField();
        jToggleButton_mostrarsenha = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JTableFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Tefone", "Senha", "Data de nasc.", "Cod.", "RG", "Endereco"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTableFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTableFuncionarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTableFuncionario);

        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_apagar.setText("Apagar");
        btn_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_apagarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cod.");

        try {
            jFormattedTextField_codigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel_nome.setText("Nome:");

        jLabel_datanascimento.setText("Data de nasc.");

        try {
            jFormattedTextField_datanascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField_datanascimento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField_datanascimentoKeyReleased(evt);
            }
        });

        jLabel_rg.setText("RG:");

        try {
            jFormattedTextField_rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel_cpf.setText("CPF:");

        try {
            jFormattedTextField_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("Idade");

        jLabel_endereco.setText("Endereco:");

        jTextField_endereco.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel_telefone.setText("Telefone:");

        try {
            jFormattedTextField_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel_senha.setText("Senha:");

        jToggleButton_mostrarsenha.setText("Mostrar");
        jToggleButton_mostrarsenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton_mostrarsenhaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextField_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_endereco)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel_rg))
                                        .addGap(174, 174, 174))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFormattedTextField_codigo)
                                        .addGap(29, 29, 29)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel_cpf)
                                    .addComponent(jLabel_nome)
                                    .addComponent(jTextField_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextField_cpf)))
                            .addComponent(jTextField_endereco)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(btn_cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_editar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPasswordField_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jToggleButton_mostrarsenha))
                                .addComponent(jLabel_senha)))))
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_apagar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(jLabel_datanascimento)
                        .addComponent(jFormattedTextField_datanascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                        .addComponent(jTextField_idade)
                        .addComponent(jLabel_telefone)
                        .addComponent(jFormattedTextField_telefone)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_rg)
                            .addComponent(jLabel_cpf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_datanascimento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextField_datanascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel_endereco)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_telefone)
                    .addComponent(jTextField_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jFormattedTextField_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton_mostrarsenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar)
                    .addComponent(btn_editar)
                    .addComponent(btn_apagar))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        try {
            // recebendo e validando dados da interface gr�fica.
            int id = 0;
            String nome = "";
            String cpf = "";
            String telefone = "";
            String senha = "";
            String datadenascimento = "";
            String codigo = "";
            String rg = "";
            String endereco = "";
            String atividade = "";
            
            if (this.jTextField_nome.getText().length() < 2) {
                throw new Mensagens("O Nome deve conter ao menos 2 caracteres.");
            } else {
                nome = this.jTextField_nome.getText();
            }
            
            if (this.jFormattedTextField_cpf.getText().length() < 11) {
                throw new Mensagens("Número de digitos no CPF insuficiente.");
            } else {
                cpf = this.jFormattedTextField_cpf.getText();
            }
            
            if (this.jFormattedTextField_telefone.getText().length() < 2) {
                throw new Mensagens("O Telefone deve conter ao menos 2 caracteres.");
            } else {
                telefone = this.jFormattedTextField_telefone.getText();
            }
            
             if (this.jPasswordField_senha.getText().length() <= 1) {
                throw new Mensagens("A Senha deve ser número e maior que um.");
            } else {
                senha = this.jPasswordField_senha.getText();
            }
             
              if (this.jFormattedTextField_datanascimento.getText().length() <= 0) {
                throw new Mensagens("A data de nascimento deve ser um número maior que 0.");
            } else {
                datadenascimento = this.jFormattedTextField_datanascimento.getText();                
            }
              if (this.jFormattedTextField_codigo.getText().length() <= 6) {
                throw new Mensagens("O Codigo deve ser um número maior que 6.");
            } else {
                codigo = this.jFormattedTextField_codigo.getText();
                
            }
            
            if (this.jFormattedTextField_rg.getText().length() <= 6) {
                throw new Mensagens("O RG deve ser um número maior que 6.");
            } else {
                rg = this.jFormattedTextField_rg.getText();
                
            }
            
            if (this.jTextField_endereco.getText().length() <= 0) {
                throw new Mensagens("O endereco deve ser maior que 0.");
            } else {
                endereco = this.jTextField_endereco.getText();
                
            }
              
              
              
              if (this.JTableFuncionario.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione um Funcionario para Alterar");
            } else {
                id = Integer.parseInt(this.JTableFuncionario.getValueAt(this.JTableFuncionario.getSelectedRow(), 0).toString());
            }
              if (this.objfuncionario.UpdateFuncionarioBD(cpf, telefone, senha, id, nome, datadenascimento, codigo, rg, endereco)) {

                // limpa os campos
                this.jTextField_nome.setText("");
                this.jFormattedTextField_cpf.setText("");
                this.jFormattedTextField_telefone.setText("");   
                this.jPasswordField_senha.setText("");
                this.jFormattedTextField_datanascimento.setText("");
                this.jFormattedTextField_codigo.setText("");
                this.jFormattedTextField_rg.setText("");
                this.jTextField_endereco.setText("");
                JOptionPane.showMessageDialog(rootPane, "Funcionario editado com Sucesso!");
                
              }
              
              System.out.println(this.objfuncionario.getMinhaLista().toString());
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um número.");
        } finally {
            carregaTabela(); // atualiza a tabela.
        }
        
        
        
    }
        
        @SuppressWarnings("unchecked")
    public void carregaTabela() {

        DefaultTableModel modelo = (DefaultTableModel) this.JTableFuncionario.getModel();
        modelo.setNumRows(0);

        ArrayList<Funcionario> minhalista = new ArrayList<>();
        minhalista = objfuncionario.getMinhaLista();

        for (Funcionario a : minhalista) {
            modelo.addRow(new Object[]{
                a.getId(),
                a.getNome(),
                a.getCpf(),
                a.getTelefone(),
                a.getSenha(),
                a.getDatadenascimento(),
                a.getCodigo(),
                a.getRg(),
                a.getEndereco(),
            });
        }
              
    }//GEN-LAST:event_btn_editarActionPerformed

    private void JTableFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableFuncionarioMouseClicked
        if (this.JTableFuncionario.getSelectedRow() != -1) {

            String nome = this.JTableFuncionario.getValueAt(this.JTableFuncionario.getSelectedRow(), 1).toString();
            String cpf = this.JTableFuncionario.getValueAt(this.JTableFuncionario.getSelectedRow(), 2).toString();
            String telefone = this.JTableFuncionario.getValueAt(this.JTableFuncionario.getSelectedRow(), 3).toString();
            String senha = this.JTableFuncionario.getValueAt(this.JTableFuncionario.getSelectedRow(), 4).toString();
            String datadenascimento = this.JTableFuncionario.getValueAt(this.JTableFuncionario.getSelectedRow(), 5).toString();
            String codigo = this.JTableFuncionario.getValueAt(this.JTableFuncionario.getSelectedRow(), 6).toString();
            String rg = this.JTableFuncionario.getValueAt(this.JTableFuncionario.getSelectedRow(), 7).toString();
            String endereco = this.JTableFuncionario.getValueAt(this.JTableFuncionario.getSelectedRow(), 8).toString();


                this.jTextField_nome.setText("");
                this.jFormattedTextField_cpf.setText("");
                this.jFormattedTextField_telefone.setText("");   
                this.jPasswordField_senha.setText("");
                this.jFormattedTextField_datanascimento.setText("");
                this.jFormattedTextField_codigo.setText("");
                this.jFormattedTextField_rg.setText("");
                this.jTextField_endereco.setText("");
                
    }//GEN-LAST:event_JTableFuncionarioMouseClicked
    
}
    private void btn_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_apagarActionPerformed
        try {
            // validando dados da interface gr�fica.
            int id = 0;
            if (this.JTableFuncionario.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione um Funcionario para APAGAR");
            } else {
                id = Integer.parseInt(this.JTableFuncionario.getValueAt(this.JTableFuncionario.getSelectedRow(), 0).toString());
            }

            // retorna 0 -> primeiro bot�o | 1 -> segundo bot�o | 2 -> terceiro bot�o
            int resposta_usuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja APAGAR este Funcionario ?");

            if (resposta_usuario == 0) {// clicou em SIM

                // envia os dados para o Aluno processar
                if (this.objfuncionario.DeleteFuncionarioBD(id)) {

                    // limpa os campos
                    this.jTextField_nome.setText("");
                    this.jFormattedTextField_cpf.setText("");
                    this.jFormattedTextField_telefone.setText("");
                    this.jPasswordField_senha.setText("");
                    this.jFormattedTextField_datanascimento.setText("");
                    this.jFormattedTextField_codigo.setText("");
                    this.jFormattedTextField_rg.setText("");
                    this.jTextField_endereco.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Funcionario Apagado com Sucesso!");

                }

            }

            System.out.println(this.objfuncionario.getMinhaLista().toString());

        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            // atualiza a tabela.
            carregaTabela();
        }
    }//GEN-LAST:event_btn_apagarActionPerformed

    private void jFormattedTextField_datanascimentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_datanascimentoKeyReleased
        // TODO add your handling code here:
        DateTimeFormatter date = DateTimeFormatter.ofPattern("dd/MM/yyyy");
    LocalDate dataNascimento = LocalDate.parse(jFormattedTextField_datanascimento.getText(), date);
    LocalDate dataAtual = LocalDate.now();
    Period periodo = Period.between(dataNascimento,dataAtual);
    String Resultado = (periodo.getYears()+ " Anos "  + periodo.getMonths() + " Meses"+" e " +  periodo.getDays() + " dias");
    jTextField_idade.setText(Resultado);
    }//GEN-LAST:event_jFormattedTextField_datanascimentoKeyReleased

    private void jToggleButton_mostrarsenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton_mostrarsenhaMouseClicked
        // TODO add your handling code here:
        if(jToggleButton_mostrarsenha.isSelected()){
            jPasswordField_senha.setEchoChar((char)0);
            jToggleButton_mostrarsenha.setText("Esconder");
        }
        else{
            jPasswordField_senha.setEchoChar('*');
            jToggleButton_mostrarsenha.setText("Mostrar");
        }
    }//GEN-LAST:event_jToggleButton_mostrarsenhaMouseClicked
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableFuncionario;
    private javax.swing.JButton btn_apagar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JFormattedTextField jFormattedTextField_codigo;
    private javax.swing.JFormattedTextField jFormattedTextField_cpf;
    private javax.swing.JFormattedTextField jFormattedTextField_datanascimento;
    private javax.swing.JFormattedTextField jFormattedTextField_rg;
    private javax.swing.JFormattedTextField jFormattedTextField_telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_cpf;
    private javax.swing.JLabel jLabel_datanascimento;
    private javax.swing.JLabel jLabel_endereco;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_rg;
    private javax.swing.JLabel jLabel_senha;
    private javax.swing.JLabel jLabel_telefone;
    private javax.swing.JPasswordField jPasswordField_senha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_endereco;
    private javax.swing.JTextField jTextField_idade;
    private javax.swing.JTextField jTextField_nome;
    private javax.swing.JToggleButton jToggleButton_mostrarsenha;
    // End of variables declaration//GEN-END:variables
}
